---
apiVersion: v1
kind: Pod
metadata:
 name: admin-portal-service-pod
 labels:
  name: admin-portal-service-pod
spec:
 containers:
 - name: admin-portal-service
   imagePullPolicy: Always
   image: 10.100.134.2:5000/bigdata-common-frontend-services/admin-portal-service
   ports:
   - containerPort: 80
   livenessProbe:
     httpGet:
       path: /
       port: 80
     initialDelaySeconds: 30
     timeoutSeconds: 1
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: admin-portal-service-rc
spec:
 replicas: 3
 selector:
  name: admin-portal-service-pod
 template:
  metadata:
   labels:
    name: admin-portal-service-pod
  spec:
   containers:
   - name: admin-portal-service-pod
     image: nginx
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: admin-portal-service-service
spec:
 type: NodePort
 ports:
 - port: 80
   nodePort: 30009
 selector:
  name: admin-portal-service-pod
