#apiVersion:r.yaml": Deployment
#kind: ReplicationController
#metadata:
#  name: heapster
#  labels:
#    name: heapster
#spec:
#  replicas: 1
#  selector:
#    name: heapster
#  template:
#    metadata:
#      labels:
#        name: heapster
#    spec:
#      containers:
#        -name: heapster
#        image: index.tenxcloud.com/google_containers/heapster:v1.1.0
#        command:
#          -/heapster
#          ---source=kubernetes:http://10.100.134.3:8080?inClusterConfig=false&kubeletHttps=true&kubeletPort=10250&useServiceAccount=true&auth=
#          ---sink=influxdb:http://10.100.134.3:8086
#
#
#

apiVersion: extensions/v1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
        imagePullPolicy: IfNotPresent
        command:
          -/heapster
          ---source=kubernetes:http://10.100.134.3:8080?inClusterConfig=false&kubeletHttps=true&kubeletPort=10250&useServiceAccount=true&auth=
          ---sink=influxdb:http://10.100.134.3:8086